In [1]:
import numpy as np
from scipy import special
import matplotlib.pyplot as plt
from scipy import integrate
from scipy import linalg as LA
import matplotlib
import math

In [4]:
Przyliżenie ciasnego wiązania. Układ periodyczny. 
Metoda LCAO z uwzględnieniem tego, że to układ periodyczny, więc funkcja falowa spełnia twierdzenie Blocha
Funkcja bazowa składa się z 2 części - Up zlokalizowanej na poszczególnych atomach R-położenie i czynnik Blochowski
Algebraiczne zagadnienie własne - uogólniony problem własny. Macierze hamiltonianu i overlapów (S)
Nadrzędne przybliżenie ciasno związanych elektronów i rozwijamy w szereg te funkcje (LCAO)
Parametryzujemy macierze overlapów i zostają tylko czynniki blochowskie
blochowskie zbudowane są z wekt. k i najbliższych sąsiadów (R1, R2, R3)
Funkcje jakie bierzemy do bazy atomowej:
w płaszczyźnie dwa orbitale sp2, a z boku planarny, bo stany pz prostopadłe do płaszczyzny.
grafen ma stożek diraca w punktcie k i to są pasma pochodzące od stanów pz, więc żeby odtworzyć fragment z przecięciem
wystarczy wziąć stany pz
ilość fcji bazy * ilość atomów w komórce czyli macierz 2x2 (gdyby wszystkie orbitale to mamy 8x8 z 2 podmacierzy)

Ri, R2, R3 najblizsi ssiedzi w położeniu atomów 
napisać procedurę generującą ścieżkę punktów k i dla każdego zbudować macierz hamiltonianu i wyrzucić 2 wart. wł.
1. ścieżka gamma K M
2. macierz hamiltonianu (a wcześniej iloczyn skalarny r1r2r3)
3. gamma, K, M współrzędne 0, 1/2, 1/3 vectors sieci odwrotnej (z b1, b2)
4. żeby jednostki wyszły e^ikR *2pi
przechodzimy z punktów M, gamma, K

In [2]:
gamma = -2.78
s0 = 0.06
e2p = 0
N = 2
H = np.zeros([N, N],dtype=np.complex_)
S = np.zeros([N, N],dtype=np.complex_)
E, K = [], []

kx = 0
ky = 0

RA =[0.666667000, 1.333333000]
R1 =[0.333333000, 1.666667000]
R2 =[1.333333000, 1.666667000]
R3 =[0.333333000, 0.666667000]
Zk = complex(e2p,0);
Jk = complex(1,1)
Cc = complex(0,1)

for k in range(60):
    if k <= 20:
        kx = 0
        ky = 0.5-0.05*k*0.5
        
    elif k > 20 and k <= 40:
        kx = 0.05*(k-20)*(1/3)
        ky = 0.05*(k-20)*(1/3)
          
    else:
        kx = (1/3)-0.05*(k-40)*(1/3)
        ky = 0.05*(k-40)*(0.5-(1/3))+(1/3)
        
    
    Rw1=2*np.pi*(kx*(RA[0]-R1[0])+ky*(RA[1]-R1[1]))
    Rw2=2*np.pi*(kx*(RA[0]-R2[0])+ky*(RA[1]-R2[1]))
    Rw3=2*np.pi*(kx*(RA[0]-R3[0])+ky*(RA[1]-R3[1]))
    
    w1=Cc*Rw1
    w2=Cc*Rw2
    w3=Cc*Rw3
    
    v1=np.exp(w1)+np.exp(w2)+np.exp(w3)
    
    H[0,0]=Zk
    H[0,1]=v1*gamma
    H[1,0]=H[0,1].conjugate()
    H[1,1]=Zk

    S[0,0]=Jk
    S[0,1]=v1*s0
    S[1,0]=S[0,1].conjugate()
    S[1,1]=Jk
    
    energies, vectors = LA.eigh(H, S)
    E.append(energies)
    K.append(k)

plt.plot(K, E, linewidth = 5)
plt.xlabel("k")
plt.ylabel("E")
plt.show()

In [3]:
E

[array([-2.62264151,  2.95744681]),
 array([-2.68274937,  3.03410522]),
 array([-2.85279586,  3.25343069]),
 array([-3.10787893,  3.58940909]),
 array([-3.41969599,  4.01190433]),
 array([-3.76388604,  4.49403078]),
 array([-4.12201516,  5.01418213]),
 array([-4.48086116,  5.55537287]),
 array([-4.83107585,  6.10397151]),
 array([-5.166021  ,  6.64862188]),
 array([-5.48092564,  7.17949998]),
 array([-5.77231294,  7.68785389]),
 array([-6.0376169 ,  8.16574533]),
 array([-6.27492476,  8.60592655]),
 array([-6.48280182,  9.00180565]),
 array([-6.6601703 ,  9.34746791]),
 array([-6.80622438,  9.63773037]),
 array([-6.92037022,  9.86821276]),
 array([ -7.00218348,  10.03541212]),
 array([ -7.05138002,  10.13677101]),
 array([ -7.06779661,  10.17073171]),
 array([ -7.04590977,  10.12547016]),
 array([-6.98034333,  9.99061268]),
 array([-6.87138251,  9.76890164]),
 array([-6.7195124 ,  9.46478043]),
 array([-6.52543246,  9.08421316]),
 array([-6.29007645,  8.63445178]),
 array([-6.01463739,

In [36]:
print(len(K))
len(E)

60


60